
export const symptoms = [
  { id: 'fever', label: 'Fever', category: 'general' },
  { id: 'headache', label: 'Headache', category: 'neurological' },
  { id: 'cough', label: 'Cough', category: 'respiratory' },
  { id: 'sore_throat', label: 'Sore Throat', category: 'respiratory' },
  { id: 'runny_nose', label: 'Runny Nose', category: 'respiratory' },
  { id: 'shortness_of_breath', label: 'Shortness of Breath', category: 'respiratory' },
  { id: 'chest_pain', label: 'Chest Pain', category: 'cardiovascular' },
  { id: 'fatigue', label: 'Fatigue', category: 'general' },
  { id: 'muscle_aches', label: 'Muscle Aches', category: 'musculoskeletal' },
  { id: 'joint_pain', label: 'Joint Pain', category: 'musculoskeletal' },
  { id: 'nausea', label: 'Nausea', category: 'gastrointestinal' },
  { id: 'vomiting', label: 'Vomiting', category: 'gastrointestinal' },
  { id: 'diarrhea', label: 'Diarrhea', category: 'gastrointestinal' },
  { id: 'abdominal_pain', label: 'Abdominal Pain', category: 'gastrointestinal' },
  { id: 'dizziness', label: 'Dizziness', category: 'neurological' },
  { id: 'confusion', label: 'Confusion', category: 'neurological' },
  { id: 'rash', label: 'Rash', category: 'dermatological' },
  { id: 'itching', label: 'Itching', category: 'dermatological' },
  { id: 'swelling', label: 'Swelling', category: 'general' },
  { id: 'loss_of_taste', label: 'Loss of Taste', category: 'respiratory' },
  { id: 'loss_of_smell', label: 'Loss of Smell', category: 'respiratory' },
  { id: 'chills', label: 'Chills', category: 'general' },
  { id: 'night_sweats', label: 'Night Sweats', category: 'general' },
  { id: 'weight_loss', label: 'Unexplained Weight Loss', category: 'general' },
  { id: 'weight_gain', label: 'Rapid Weight Gain', category: 'general' },
  { id: 'palpitations', label: 'Heart Palpitations', category: 'cardiovascular' },
  { id: 'back_pain', label: 'Back Pain', category: 'musculoskeletal' },
  { id: 'neck_pain', label: 'Neck Pain', category: 'musculoskeletal' },
  { id: 'eye_pain', label: 'Eye Pain', category: 'ophthalmological' },
  { id: 'blurred_vision', label: 'Blurred Vision', category: 'ophthalmological' },
  { id: 'ear_pain', label: 'Ear Pain', category: 'ent' },
  { id: 'hearing_loss', label: 'Hearing Loss', category: 'ent' },
  { id: 'frequent_urination', label: 'Frequent Urination', category: 'genitourinary' },
  { id: 'painful_urination', label: 'Painful Urination', category: 'genitourinary' },
  { id: 'blood_in_urine', label: 'Blood in Urine', category: 'genitourinary' },
  { id: 'constipation', label: 'Constipation', category: 'gastrointestinal' },
  { id: 'heartburn', label: 'Heartburn', category: 'gastrointestinal' },
  { id: 'difficulty_swallowing', label: 'Difficulty Swallowing', category: 'gastrointestinal' },
  { id: 'sleep_problems', label: 'Sleep Problems', category: 'neurological' },
  { id: 'memory_problems', label: 'Memory Problems', category: 'neurological' },
  { id: 'mood_changes', label: 'Mood Changes', category: 'psychological' },
  { id: 'anxiety', label: 'Anxiety', category: 'psychological' },
  { id: 'depression', label: 'Depression', category: 'psychological' }
];

export const categoryLabels: { [key: string]: string } = {
  general: 'General Symptoms',
  respiratory: 'Respiratory',
  cardiovascular: 'Cardiovascular',
  gastrointestinal: 'Gastrointestinal',
  neurological: 'Neurological',
  musculoskeletal: 'Musculoskeletal',
  dermatological: 'Skin & Hair',
  ophthalmological: 'Eyes',
  ent: 'Ear, Nose & Throat',
  genitourinary: 'Urinary System',
  psychological: 'Mental Health'
};
